name: Trigger Jenkins Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Build
        env:
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          curl -X POST https://a04d-59-96-56-57.ngrok-free.app/job/node/build \
          --user $JENKINS_USERNAME:$JENKINS_API_TOKEN





