name: QA Automation
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Build
    runs-on: jenkins/jenkins:latest
    steps:
      - name: "Trigger jenkins job"
        uses: umutcolak/jenkins-trigger-job@main
        with:
          jenkins-url: ${{secrets.JENKINS_URL}}
          user: ${{secrets.JENKINS_USERNAME}}
          jenkins-token: ${{secrets.JENKINS_API_TOKEN}}
          job-name: ${{secrets.JENKINS_JOB_NAME}}
          job-params: '{"branch_name": "${{github.ref}}"}'
